export const places = {
    "amh":[
        {name: "Addis Ababa","Addis Ababa":"አዲስ አበባ"},
        {name:"Adola/Kibremengist","Adola/Kibremengist":"አዶላ/ክብረ-መንግስት"},
        {name:"Agaro","Agaro":"አጋሮ"},
        {name:"Alamata","Alamata":"አላማታ"},
        {name:"Arba Minch","Arba Minch":"አርባ ምንጭ"},
        {name:"Asosa","Asosa":"አሶሳ"},
        {name:"Bahir Dar","Bahir Dar":"ባህር ዳር"},
        {name:"Bedele","Bedele":"በደሌ"},
        {name:"Bichena","Bichena":"ቢቸና"},
        {name:"Bonga","Bonga":"ቦንጋ"},
        {name:"Bule Hora","Bule Hora":"ቡሌ ሆራ"},
        {name:"Bure","Bure":"ቡሬ"},
        {name:"Chagni","Chagni":"ቻግኒ"},
        {name:"Dangla","Dangla":"ዳንግላ"},
        {name:"Debre Birhan","Debre Birhan":"ደብረ ብርሃን"},
        {name:"Debre Markos","Debre Markos":"ደብረ ማርቆስ"},
        {name:"Debre Tabor","Debre Tabor":"ደብረ ታቦር"},
        {name:"Dembecha","Dembecha":"ደምበጫ"},
        {name:"Dembidolo","Dembidolo":"ደምቢዶሎ"},
        {name:"Dessie","Dessie":"ደሴ"},
        {name:"Dilla","Dilla":"ዲላ"},
        {name:"Dire Dawa","Dire Dawa":"ድሬዳዋ"},
        {name:"Enjibara","Enjibara":"እንጅባራ"},
        {name:"Finote Selam","Finote Selam":"ፍኖተ ሰላም"},
        {name:"Gambela","Gambela":"ጋምቤላ"},
        {name:"Gimbi","Gimbi":"ጊምቢ"},
        {name:"Gondar","Gondar":"ጎንደር"},
        {name:"Harar","Harar":"ሐረር"},
        {name:"Hawassa","Hawassa":"ሀዋሳ"},
        {name:"Jijiga","Jijiga":"ጅጅጋ"},
        {name:"Jimma","Jimma":"ጅማ"},
        {name:"Kombolcha","Kombolcha":"ኮምቦልቻ"},
        {name:"Kosober","Kosober":"ኮሶበር"},
        {name:"Kulbi Gebriel","Kulbi Gebriel":"ቁልቢ ገብርኤል"},
        {name:"Mekane-Selam","Mekane-Selam":"መካነ-ሰላም"},
        {name:"Mekele","Mekele":"መቀሌ"},
        {name:"Mendi Nejo","Mendi Nejo":"መንዲ ነጆ"},
        {name:"Mertole-Maryam","Mertole-Maryam":"መርጦለ-ማርያም"},
        {name:"Metu","Metu":"መቱ"},
        {name:"Mizan","Mizan":"ሚዛን"},
        {name:"Motta","Motta":"ሞጣ"},
        {name:"Moyale","Moyale":"ሞያሌ"},
        {name:"Negele Borana","Negele Borana":"ነገሌ ቦረና"},
        {name:"Nekemte","Nekemte":"ነቀምት"},
        {name:"Robe","Robe":"ሮቤ"},
        {name:"Semera","Semera":"ሰመራ"},
        {name:"Wolayita Sodo","Wolayita Sodo":"ወላይታ ሶዶ"},
        {name:"Woldiya","Woldiya":"ወልዲያ"},
        {name:"Yabelo","Yabelo":"ያቤሎ"},
    ],
    "orm":[
        {name:"Addis Ababa","Addis Ababa":"FinFinnee"},
        {name:"Adola/Kibremengist","Adola/Kibremengist":"Adoolaa"},
        {name:"Agaro","Agaro":"Aggaarroo"},
        {name:"Alamata","Alamata":"Alaammata"},
        {name:"Arba Minch","Arba Minch":"Arbaa Minchii"},
        {name:"Asosa","Asosa":"Assoosa"},
        {name:"Bahir Dar","Bahir Dar":"Baahir Daar"},
        {name:"Bedele","Bedele":"Badaalee"},
        {name:"Bichena","Bichena":"Bichanaa"},
        {name:"Bonga","Bonga":"Bongaa"},
        {name:"Bule Hora","Bule Hora":"Bulee Hooraa"},
        {name:"Bure","Bure":"Burree"},
        {name:"Chagni","Chagni":"Chaaginii"},
        {name:"Dangla","Dangla":"Dangala"},
        {name:"Debre Birhan","Debre Birhan":"Dabra Birhaan"},
        {name:"Debre Markos","Debre Markos":"Dabra Marqoos"},
        {name:"Debre Tabor","Debre Tabor":"Dabra Taaboor"},
        {name:"Dembecha","Dembecha":"Dambacaa"},
        {name:"Dembidolo","Dembidolo":"Dambidoolo"},
        {name:"Dessie","Dessie":"Dasee"},
        {name:"Dilla","Dilla":"Dillaa"},
        {name:"Dire Dawa","Dire Dawa":"Dirree Dhawaa"},
        {name:"Enjibara","Enjibara":"Enjibaraa"},
        {name:"Finote Selam","Finote Selam":"Finotee Seelaam"},
        {name:"Gambela","Gambela":"Gambellaa"},
        {name:"Gimbi","Gimbi":"Giimbii"},
        {name:"Gondar","Gondar":"Goondar"},
        {name:"Harar","Harar":"Harar"},
        {name:"Hawassa","Hawassa":"Hawaassa"},
        {name:"Jigjiga","Jigjiga":"Jijjigaa"},
        {name:"Jimma","Jimma":"Jimmaa"},
        {name:"Kombolcha","Kombolcha":"Kombolchaa"},
        {name:"Kosober","Kosober":"Kosobaarii"},
        {name:"Kulbi Gebriel","Kulbi Gebriel":"Kulbii Gebri’eel"},
        {name:"Mekane-Selam","Mekane-Selam":"Makaana-Salaam"},
        {name:"Mekele","Mekele":"Maqalee"},
        {name:"Mendi Nejo","Mendi Nejo":"Mandii Najjoo"},
        {name:"Mertole-Maryam","Mertole-Maryam":"Marxoola-Maariyaam"},
        {name:"Metu","Metu":"Maatu"},
        {name:"Mizan","Mizan":"Miizaan"},
        {name:"Motta","Motta":"Mooyyaalee"},
        {name:"Moyale","Moyale":"Mooyyaalee"},
        {name:"Negele Borana","Negele Borana":"Nagelee Booranaa"},
        {name:"Nekemte","Nekemte":"Naqamtee"},
        {name:"Robe","Robe":"Robbe"},
        {name:"Semera","Semera":"Samaraa"},
        {name:"Wolayita Sodo","Wolayita Sodo":"Walayittaa Soddoo"},
        {name:"Woldiya","Woldiya":"Waldiyaa"},
        {name:"Yabelo","Yabelo":" Yaabeelloo"},
    ],
    "tgr":[
        {name:"Addis Ababa","Addis Ababa":"ኣዲስ ኣበባ"},
        {name:"Adola/Kibremengist","Adola/Kibremengist":"ኣዶላ"},
        {name:"Agaro","Agaro":"ኣጋሮ"},
        {name:"Alamata","Alamata":"ኣላማታ"},
        {name:"Arba Minch","Arba Minch":"ኣርባ ምንጭ"},
        {name:"Asosa","Asosa":"ኣሶሳ"},
        {name:"Bahir Dar","Bahir Dar":"ባህር ዳር"},
        {name:"Bedele","Bedele":"በደሌ"},
        {name:"Bichena","Bichena":"ቢቸና"},
        {name:"Bonga","Bonga":"ቦንጋ"},
        {name:"Bule Hora","Bule Hora":"ቡሌ ሆራ"},
        {name:"Bure","Bure":"ቡሬ"},
        {name:"Chagni","Chagni":"ቻግኒ"},
        {name:"Dangla","Dangla":"ዳንግላ"},
        {name:"Debre Birhan","Debre Birhan":"ደብረ ብርሃን"},
        {name:"Debre Markos","Debre Markos":"ደብረ ማርቆስ"},
        {name:"Debre Tabor","Debre Tabor":"ደብረ ታቦር"},
        {name:"Dembecha","Dembecha":"ደምበጫ"},
        {name:"Dembidolo","Dembidolo":"ደምቢዶሎ"},
        {name:"Dessie","Dessie":"ደሴ"},
        {name:"Dilla","Dilla":"ዲላ"},
        {name:"Dire Dawa","Dire Dawa":"ድሬዳዋ"},
        {name:"Enjibara","Enjibara":"እንጅባራ"},
        {name:"Finote Selam","Finote Selam":"ፍኖተ ሰላም"},
        {name:"Gambela","Gambela":"ጋምቤላ"},
        {name:"Gimbi","Gimbi":"ጊምቢ"},
        {name:"Gondar","Gondar":"ጎንደር"},
        {name:"Harar","Harar":"ሐረር"},
        {name:"Hawassa","Hawassa":"ሀዋሳ"},
        {name:"Jigjiga","Jigjiga":"ጅጅጋ"},
        {name:"Jimma","Jimma":"ጅማ"},
        {name:"Kombolcha","Kombolcha":"ኮምቦልቻ"},
        {name:"Kosober","Kosober":"ኮሶበር"},
        {name:"Kulbi Gebriel","Kulbi Gebriel":"ቁልቢ ገብርኤል"},
        {name:"Mekane-Selam","Mekane-Selam":"መካነ-ሰላም"},
        {name:"Mekele","Mekele":"መቀሌ"},
        {name:"Mendi Nejo","Mendi Nejo":"መንዲ ነጆ"},
        {name:"Mertole-Maryam","Mertole-Maryam":"መርጦለ-ማርያም"},
        {name:"Metu","Metu":"መቱ"},
        {name:"Mizan","Mizan":"ሚዛን"},
        {name:"Motta","Motta":"ሞጣ"},
        {name:"Moyale","Moyale":"ሞያሌ"},
        {name:"Negele Borana","Negele Borana":"ነገሌ ቦረና"},
        {name:"Nekemte","Nekemte":"ነቀምት"},
        {name:"Robe","Nekemte":"ሮቤ"},
        {name:"Semera","Semera":"ሰመራ"},
        {name:"Wolayita Sodo","Wolayita Sodo":"ወላይታ ሶዶ"},
        {name:"Woldiya","Woldiya":"ወልዲያ"},
        {name:"Yabelo","Yabelo":"ያቤሎ"},
    ],
    "eng":[
        {name:"Addis Ababa","Addis Ababa":"Addis Ababa"},
        {name:"Adola/Kibremengist","Adola/Kibremengist":"Adola/Kibremengist"},
        {name:"Agaro","Agaro":"Agaro"},
        {name:"Alamata","Alamata":"Alamata"},
        {name:"Arba Minch","Arba Minch":"Arba Minch"},
        {name:"Asosa","Asosa":"Asosa"},
        {name:"Bahir Dar","Bahir Dar":"Bahir Dar"},
        {name:"Bedele","Bedele":"Bedele"},
        {name:"Bichena","Bichena":"Bichena"},
        {name:"Bonga","Bonga":"Bonga"},
        {name:"Bule Hora","Bule Hora":"Bule Hora"},
        {name:"Bure","Bure":"Bure"},
        {name:"Chagni","Chagni":"Chagni"},
        {name:"Dangla","Dangla":"Dangla"},
        {name:"Debre Birhan","Debre Birhan":"Debre Birhan"},
        {name:"Debre Markos","Debre Markos":"Debre Markos"},
        {name:"Debre Tabor","Debre Tabor":"Debre Tabor"},
        {name:"Dembecha","Dembecha":"Dembecha"},
        {name:"Dembidolo","Dembidolo":"Dembidolo"},
        {name:"Dessie","Dessie":"Dessie"},
        {name:"Dilla","Dilla":"Dilla"},
        {name:"Dire Dawa","Dire Dawa":"Dire Dawa"},
        {name:"Enjibara","Enjibara":"Enjibara"},
        {name:"Finote Selam","Finote Selam":"Finote Selam"},
        {name:"Gambela","Gambela":"Gambela"},
        {name:"Gimbi","Gimbi":"Gimbi"},
        {name:"Gondar","Gondar":"Gondar"},
        {name:"Harar","Harar":"Harar"},
        {name:"Hawassa","Hawassa":"Hawassa"},
        {name:"Jigjiga","Jigjiga":"Jigjiga"},
        {name:"Jimma","Jimma":"Jimma"},
        {name:"Kombolcha","Kombolcha":"Kombolcha"},
        {name:"Kosober","Kosober":"Kosober"},
        {name:"Kulbi Gebriel","Kulbi Gebriel":"Kulbi Gebriel"},
        {name:"Mekane-Selam","Mekane-Selam":"Mekane-Selam"},
        {name:"Mekele","Mekele":"Mekele"},
        {name:"Mendi Nejo","Mendi Nejo":"Mendi Nejo"},
        {name:"Mertole-Maryam","Mertole-Maryam":"Mertole-Maryam"},
        {name:"Metu","Metu":"Metu"},
        {name:"Mizan","Mizan":"Mizan"},
        {name:"Motta","Motta":"Motta"},
        {name:"Moyale","Moyale":"Moyale"},
        {name:"Negele Borana","Negele Borana":"Negele Borana"},
        {name:"Nekemte","Nekemte":"Nekemte"},
        {name:"Robe","Robe":"Robe"},
        {name:"Semera","Semera":"Semera"},
        {name:"Wolayita Sodo","Wolayita Sodo":"Wolayita Sodo"},
        {name:"Woldiya","Woldiya":"Woldiya"},
        {name:"Yabelo","Yabelo":"Yabelo"},
    ]
}
